version: 2.1

jobs:
  init:
    docker:
      # Use the same Docker base as the project
      - image: circleci/python:3.10-buster-node-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run python lint
          command: |
            . capstone/bin/activate
            make lint 
      # run hadolint!
      - run:
          name: run hado lint
          command: |
            . capstone/bin/activate
            #make hadolint
      - run: 
          name: run docker build
          command: |
            docker --version
            docker images ls
            . capstone/bin/activate
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t capstone:$TAG .
            docker tag capstone $DOCKER_USER/capstone:$TAG
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/capstone:$TAG



  #build:
  #  machine: true
  #  steps:
  #    - checkout
  #    - restore_cache:
  #        keys:
  #        - v1-dependencies-{{ checksum "requirements.txt" }}
  #        # fallback to using the latest cache if no exact match is found
  #        - v1-dependencies-
  #    - run: 
  #        name: run docker build
  #        command: |
  #          docker --version
  #          docker images ls
  #          . capstone/bin/activate
  #          TAG=0.1.$CIRCLE_BUILD_NUM
  #          docker build -t capstone:$TAG .
  #          docker tag capstone $DOCKER_USER/capstone:$TAG
  #          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  #          docker push $DOCKER_USER/capstone:$TAG

workflows:
  default:
    jobs:
      - init
#      - build:
#          requires: [init]