version: 2.1

#orbs:
#  docker: circleci/docker@2.0.1

jobs:
  init:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASS  # context / project UI env-var reference    
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run python lint
          command: |
            . capstone/bin/activate
            make lint 
      # run hadolint!
      - run:
          name: run hado lint
          command: |
            . capstone/bin/activate
            #make hadolint
      - run:
          name: Install Docker client
          command: apt-get install docker-ce-cli
      - run: 
          name: run docker build
          command: |
            docker --version
            docker images
      #      #. capstone/bin/activate
      #      #TAG=0.1.$CIRCLE_BUILD_NUM
      #      #docker build -t capstone:$TAG .
      #     #docker tag capstone $DOCKER_USER/capstone:$TAG
      #      #echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #      #docker push $DOCKER_USER/capstone:$TAG

workflows:
  default:
    jobs:
      - init
      #https://circleci.com/developer/orbs/orb/circleci/docker#usage-build-and-update
      #- docker/publish:
      #    deploy: false
      #    #image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME          
      #    use-docker-credentials-store: true
      #    tag: 0.1.$CIRCLE_BUILD_NUM
      #    image: brayssa/capstone          
      #    requires: [init]

