version: 2.1

jobs:
  build:
    docker:
      # https://circleci.com/developer/images/image/cimg/python#image-name
      - image: cimg/python:3.10.1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: ~/repo
    steps:
      - checkout
      # https://circleci.com/docs/2.0/building-docker-images/ 
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "requirements.txt" }}
      #    # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint
      - run:
          name: run python lint
          command: |
            . capstone/bin/activate
            make lint 
      # run hadolint
      - run:
          name: run hado lint
          command: |
            . capstone/bin/activate
            make hadolint
      # build local image
      - run: 
          name: run docker build
          command: |
            . capstone/bin/activate
            make build-image PROJECT=$CAPSTONE_PROJECT
            #docker --version
            #docker build -t $CAPSTONE_PROJECT .
      # push image to my docker.io repo
      - run: 
          name: run docker push
          command: |
            . capstone/bin/activate
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker tag $CAPSTONE_PROJECT $DOCKER_USER/$CAPSTONE_PROJECT:$TAG
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/$CAPSTONE_PROJECT:$TAG

workflows:
  default:
    jobs:
      - build 
