version: 2.1

jobs:
  build:
    docker:
      # Use the same Docker base as the project
      #- image: python:3.7.3-stretch
      - image: cimg/python:3.10.1
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "requirements.txt" }}
      #    # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-
      - run:
          name: start docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo systemctl start docker
            docker --version
      - run:
          name: install dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            make install
            # Install hadolint
            #wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            #sudo chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run python lint
          command: |
            . capstone/bin/activate
            make lint 
      # run hadolint!
      - run:
          name: run hado lint
          command: |
            . capstone/bin/activate
            #make hadolint
 
      # build and push Docker image
      - run:
          name: run docker build
          command: |
            . capstone/bin/activate
            docker --version                      
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t capstone:$TAG .
            docker tag capstone $DOCKER_USER/capstone:$TAG
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/capstone:$TAG

workflows:
  default:
    jobs:
      - build
      #- buildImage:
      #    requires: [build]