apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: brayssa/capstone:TAG
          imagePullPolicy: IfNotPresent
          name: capstone
          ports:
            - containerPort: 80